### ISSUE TITLE
when mapServers is empty, where will have problems

### ISSUE THREAD

**Issue by AnchorRen** [aebadirad/Leaflet.AutoLayers#1]
you said the 'mapServers' is OPTIONAL,but when i set config
like this:
`var config = {`
       `overlays:overlays,`
        `selectedBasemap: 'OpenStreetMap',`
        `selectedOverlays: ["cities"],`
        `baseLayers:baseLayers,`
   `};`
there will be a problem in  leaflet-autolayers.js:397 
ERROR is : Uncaught TypeError: Cannot read property 'length' of undefined

**Comment by aebadirad** [comment]
Good find. Updated on master branch to fix this bug.
