### ISSUE TITLE
Uncaught ReferenceError: map is not defined

### ISSUE THREAD

**Issue by CleberDSantos** [aebadirad/Leaflet.AutoLayers#11]
In _initMaps function, the map var is not defined on line 391 and 393.

![image](https://user-images.githubusercontent.com/1626423/31779610-470b1956-b4d2-11e7-8176-0893782557d6.png)

![image](https://user-images.githubusercontent.com/1626423/31779560-28ba0ebc-b4d2-11e7-9907-3bed323c09d8.png)

**Comment by CleberDSantos** [comment]
I changed and it's work fine now

![image](https://user-images.githubusercontent.com/1626423/31779858-e2208e44-b4d2-11e7-91fb-4f2a5eb4177e.png)

**Comment by aebadirad** [comment]
What version of leaflet are you running with this?

I probably need to upgrade the branch to the 1.x release line to support the most recent release.

**Comment by CleberDSantos** [comment]
I'm using Leaflet 0.7.7

**Comment by whelks-chance** [comment]
I'm getting some similar, but not identical issues. The fix suggested just led to more errors within leaflet itself. v0.7.7 

An issue which may be related - in the main html/ js block for my site, the leaflet map object wasn't called "map". Renaming it fixed the issue, so I assume the same self._map issue is to blame.

**Comment by CleberDSantos** [comment]
You can to close this issue, because I don't have more it
