### ISSUE TITLE
Add Geoserver in Mapservers options

### ISSUE THREAD

**Issue by diegomonteiro** [aebadirad/Leaflet.AutoLayers#3]
Hello,
I have a GeoServer server and want to add it in the options "Mapservers", is there any example of such integration?

**Comment by aebadirad** [comment]
There's a few different ways. If your GeoServer is exporting the default WMS maps, you can just use the WMS capability.

If you're using WFS, I will probably have to add the WFS capability in. But that is something that can be done pretty easily upon request.

**Comment by diegomonteiro** [comment]
Thanks for your attention, its worked
