### ISSUE TITLE
Not compatible with recent browser versions?

### ISSUE THREAD

**Issue by whelks-chance** [aebadirad/Leaflet.AutoLayers#6]
line 502 has 

`	_parseESRILayer: function(mapServer, layer, folder = false) {`

which uses default parameters. While this is compatible with most browsers, it is quite a new addition to EMCA6.

https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Functions/Default_parameters#Browser_compatibility

Is it perhaps worth avoiding such features until the spec has been around for a while longer?

Or, even better, can anyone suggest a block of code which tests if this feature is available, and provide a fallback if it doesn't work?

**Comment by aebadirad** [comment]
I'll change this to assume the static parameters with a false being passed rather than defaulted. It is possible some folks still have to use IE11 or earlier versions of FireFox or android browser.

That should alleviate the concern.

**Comment by whelks-chance** [comment]
Great, thanks. I considered doing the same and doing submitting a pull request, but it's pretty small thing. I was amazed how many browsers in my office at work were incompatible with it actually.

I never did figure out how to test for the feature directly, btw.

I appreciate your efforts, cheers.

**Comment by aebadirad** [comment]
Sorry it's taken so long, million other things on my plate, but I got around to updating it with a default boolean parameter passed.

Going forward with the .7.x leaflet version of this plugin I'll try to make sure to not include anything above EMCA 5.

**Comment by whelks-chance** [comment]
That works great, thanks very much!

Hopefully some day we can rely on everyone having updated browsers, but I can't see that happening anytime soon...

Cheers,
