### ISSUE TITLE
Support i18n

### ISSUE THREAD

**Issue by diegomonteiro** [aebadirad/Leaflet.AutoLayers#7]
Please implement i18n internationalization support for better customization of the system, if need be, I can lend a hand with Pull Requests.

**Comment by aebadirad** [comment]
This is something I hadn't considered. I'll make sure to build string internationalization into the 1.0 leaflet version of autolayers going forward.

For the .77 leaflet compatible version, what would you need changed to make it usable in an international/multilingual setting?

**Comment by diegomonteiro** [comment]
I sent a pull request to fix this. Make sure it is correct. However I did run around I did not have time to correctly implement the i18n standard.
